# Maven
- task: mabl-azure-devops-extension@1
  inputs:
    apiKey: 'dX31Zr0YL6MM5upaCDwAlA'
    applicationId: 'mD9Sc27RikI2tbhhaA9EFw-a'
    environmentId: 'XNMUsR6YHZUjFkaojwIuSQ-e'
    labels: 'qa'
